version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD:  "Tbmjg749ns"
    env_file: ./blog_backend/.env
  django:
    build: ./blog_backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file: ./blog_backend/.env
    volumes:
      - ./blog_backend:/blog/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment: 
      DB_HOST: "db"
      DB_NAME: "Blog-django-react"
      DB_USER: "postgres"
      DB_PASS: "Tbmjg749ns"
  frontend:
    build: ./blog_frontend
    command: ["npm", "start"]
    env_file: ./blog_frontend/.env
    volumes:
      - ./blog_frontend:/blog/frontend
      - node-modules:/blog/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules: